name: Automation Framework CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Run UI Tests
      # Sử dụng xvfb-run để giả lập màn hình hiển thị (display) cho trình duyệt trên Linux server
      run: xvfb-run mvn clean test
      continue-on-error: true # Cho phép step tiếp theo chạy dù test có fail

    - name: Generate Allure Report
      if: always()
      run: mvn allure:report

    - name: Upload Allure Report Artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-html-report
        path: target/site/allure-maven-plugin/
        retention-days: 7

    - name: Upload Raw Diagnostics Artifacts
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: raw-diagnostics
        path: reports/
        retention-days: 7